compressionLevel: mixed

enableGlobalCache: false

initScope: npmScopes

nodeLinker: node-modules

npmScopes:
  fortawesome:
    npmAlwaysAuth: true
    npmAuthToken: DBB3DC19-9679-4EBE-B370-1A89E00CE47E
    npmRegistryServer: 'https://npm.fontawesome.com'

yarnPath: .yarn/releases/yarn-4.0.0.cjs
